#google:
#        client:
#            clientId: 1040720357863-9av4d4fgkt6hp1lv7adeh4f5vashvgcd.apps.googleusercontent.com
#            clientSecret: eYkGA4qN3jTi_NmTBf25xYm9
#            accessTokenUri: https://www.googleapis.com/oauth2/v4/token
#            userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
#            tokenName: authorization_code
#            scope: https://www.googleapis.com/auth/userinfo.profile
#            clientAuthenticationScheme: form
#        resource:
#            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
#
#github:
#  client:
#    clientId: bd1c0a783ccdd1c9b9e4
#    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
#    accessTokenUri: https://github.com/login/oauth/access_token
#    userAuthorizationUri: https://github.com/login/oauth/authorize
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://api.github.com/user
#
#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmesecret
#      scope: read,write
#      auto-approve-scopes: '.*'

security:
  oauth2:
    client:
      clientId: bd1c0a783ccdd1c9b9e4
      clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user

logging:
  level:
    org.springframework.security: DEBUG